### ISSUE TITLE
after installing call-graph by MELPA, the graph generated is "◆ nil"

### ISSUE THREAD

**Issue by RGNagel** [beacoder/call-graph#12]
I have been using gtags in a project of mine just fine. However, when cursor is over a function and I call _call-graph_, the graph generated is empty: "◆ nil"

For what I understood from the readme, if I already have global database generated in the souce code then the procedure above should work. Right? 

Thank you for this package. Very useful. I have been doing this kind of graph by "hand" when dealing with many nested functions.

**Comment by beacoder** [comment]
Hi RGNagel, 
First, thanks for using call-graph, glad call-graph is useful for your work.
As for the issue you mentioned, you could check this variable first `cg-search-filters'.
its default value is ("grep -E \"\\.(cpp|cc|c):\"").
which means only function references in cpp/cc/c files are used.
And if this issue still exit, you could try to debug call-graph by
using edebug-defun on function entry function `call-graph', and see
where the issue originated.
thanks again for using this.

**Comment by RGNagel** [comment]
Sorry me for the late reply. 

The variable `cg-search-filters` is the default. 

Then I tried to debug `call-graph` by `edebug-defun`: I called `edebug-defun` over `call-graph` in the source file `~/.emacs.d/elpa/call-graph-20190104.507/call-graph.el`. Afterwards I executed `call-graph` over few different functions in some *.c files of different projects. Every call seems to execute normally (i.e. no error or messages) and they end up as "◆ nil".

If I did something wrong above let me know. Also, If you have any other suggestion I can try to workaround this I would appreciate.

Thank you again!

**Comment by RGNagel** [comment]
*> Please make sure you have installed GNU-Global.*
Yes it's installed.

> *then check if you have executed gtags to generate tags file in your
source directory.*
Yes. Files GPATH, GRTAGS, GTAGS. I use ggtags normally in the projects so
it should work.

> then say if you want to generate call-graph for function function-example.
> make sure following command do have output .
> "global -a --result=grep -r function-example"
Yes. The above command reproduce outputs for different functions.


Any idea about what else could I try to find the issue?
Thanks again!

**Comment by beacoder** [comment]
edebug-defun on cg--search-callers to check if callers are found.
then edebug-defun on cg--build-hierarchy to check if callers are properly populated hierarchy structure.
last edebug-defun cg--display-hierarchy to check if callers in hierarchy are properly inserted into call-graph tree.

**Comment by RGNagel** [comment]
I think I found the origin. Within function `cg--search-callers`, the function `cg--find-caller` is called:

    ...
    (when-let ((caller-info (and reference (cg--find-caller reference func))))
    ...

where `cg--find-caller` function is always returning `nil` even arguments `reference` and `func` being valid for different function over which I call `call-graph`. 

The problem now is that `edebug-defun` does not work over `cg--find-caller` since it messages _invalid-read-syntax "Expected one of"_ (function `edebug-match-&or` of file `edebug.el`). I am stuck here.

If I overcome this point somehow I will update this. Thanks again!

**Comment by beacoder** [comment]
welcome, let me know if you got other question, thanks.

**Comment by beacoder** [comment]
Hi e66,
since call-graph is relying on GNU-Global to find caller information, so probably it will not work in windows environment..

**Comment by e66** [comment]
Believe it or not, Gnu-Global has win version  to choose from, and it works well in emacs(win version).

**Comment by beacoder** [comment]
Wow, that's great.

**Comment by RGNagel** [comment]
> I think I found the origin. Within function `cg--search-callers`, the function `cg--find-caller` is called:
> 
> ```
> ...
> (when-let ((caller-info (and reference (cg--find-caller reference func))))
> ...
> ```
> 
> where `cg--find-caller` function is always returning `nil` even arguments `reference` and `func` being valid for different function over which I call `call-graph`.
> 
> The problem now is that `edebug-defun` does not work over `cg--find-caller` since it messages _invalid-read-syntax "Expected one of"_ (function `edebug-match-&or` of file `edebug.el`). I am stuck here.
> 
> If I overcome this point somehow I will update this. Thanks again!

Hello again @beacoder 

I am trying to fix this issue again (I really want to use call-graph).
I am  debugging _edebug_ over function _cg--search-callers_. This time I found the following message:

> Args out of range: [cl-struct-call-graph #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ()) #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data (root-function ("/home/rgnagel/Desktop/packet_forwarder/lora_pkt_fwd/src/lora_pkt_fwd.c:273")))], 3

The message came from the following line (in **bold**):

> (defun cg--search-callers (call-graph func depth)
>   "In CALL-GRAPH, given FUNC, search callers deep to level DEPTH."
>   (when-let ((next-depth (and (> depth 0) (1- depth)))
>              (short-func (cg--extract-method-name func))
>              **(data-mode (call-graph--data-mode call-graph)))**
> ...

Any idea how can we fix it?

Thank you!
