### ISSUE TITLE
syntax rules

### ISSUE THREAD

**Issue by sakopzon** [beacoder/call-graph#18]
Is it possible to make a rule for macros which define functions? For example if I have a macro like:

`#define DEFINE_FUNC(func_name, arg_for_g) { 
    void func_name (arg_for_g) { 
        g(arg_for_g); 
     } 
}
DEFINE_FUNC(f, "Hello")`

When I call call-graph on g(), how can I make call-graph print "func_name" but not "DEFINE_FUNC"?
I understand that gtags returns DEFINE_FUNC as the caller of g, but I am sure there is a way to define a rule which will substitute DEFINE_FUNC with the first word after the "("...
Please advice how can I implement it.
Thanks :)

**Comment by beacoder** [comment]
you could look into cg--show-function-args in cg-global.
basic, the function name is generated by imenu which uses some kind of regexp to extract data.
for your specific needs, I can only say, not easy to implement without breaking current behaviour.
