### ISSUE TITLE
我遇到一点emacs27环境下的配置问题

### ISSUE THREAD

**Issue by e665107** [beacoder/call-graph#19]
配置提示这个Symbol’s function definition is void: cg--handle-root-function，同时key  map中的map无效，你能提供一个可使用的配置莫，谢谢

**Comment by beacoder** [comment]
hi, this lib is mainly used for cpp.
for the configuration, you could check out:
https://github.com/beacoder/dot-emacs/blob/master/.emacs.d/elisp/init-3rd-party.el
