### ISSUE TITLE
Not work in tramp mode

### ISSUE THREAD

**Issue by GitKKg** [beacoder/call-graph#20]
The tool is great, very good in local environment.
But get no any output when project is in remote tramp mode.

I think it's should be relevant with file path issue, maybe need to handle "/ssh:usr@server#portnumber:" such like string in path by  file-remote-p series interface, but not sure if right or how.

Could you support this tool in tramp?
It will be very versatile then.

Thanks!

**Comment by beacoder** [comment]
Hi,

Glad to hear that you enjoyed this package.
As for supporting this in tramp, it's not gonna be easy, you could check this out:
https://www.reddit.com/r/emacs/comments/soe7u/gtags_and_tramp/

but I will take some time to do the study and see if it's possible to implement this feature.

Thanks.

Brs

**Comment by beacoder** [comment]
Hi,

I come up with this idea:

1.generate gtags in your remote
2.start emacs and start call-graph-server-mode on remote
3.config call-graph-client to get function reference from remote.

basically, local call-graph fire query request to remote call-graph, then remote call-graph will
invoke the global command to get the reference information and return back to local call-graph.
then this will work.

not sure if this is acceptable for you ?

Thanks.

Brs.

**Comment by beacoder** [comment]
Hi,

I gave this idea another thought, and even though I can implement this feature, due to the network latency the whole using experience will not be as good as when used in locally.

So I don't think there's much value in adding this new feature..
Sorry for the inconvenience.

Brs

**Comment by GitKKg** [comment]
Hi, sorry for the late to reply.
Did you found very slow when accompanying with tramp?
Maybe it's some config issue.
As my experience, for just linux kernel project,tramp+gtags just work well,every one time of definition jumping of symbol , takes about 1s more,less than 2s.
if you found it very slow , maybe due to projectile, just disable it.

Paste one solution I met in cflow tool with tramp, maybe similar with the context of call-graph ,hope trigger some thought:
(defun yyc/cflow-function (function-name)
  "Get call graph of inputed function. "
  ;use gtags to get symbole in current point
  (interactive  (list (helm-gtags--read-tagname 'function-name) ))
  ;(interactive (list (car (senator-jump-interactive "Function name: " nil nil nil))))
  ;; tramp mode will get user@host... before path,so must cut off it.
  (if (file-remote-p (buffer-file-name))
      (setq trueFileName
            (nth 2 (split-string (buffer-file-name) "\:" ) )
            )
    setq trueFileName buffer-file-name)
  (setq cmd (format "cflow  -b --main=%s %s" function-name trueFileName))
  
  (setq cflow-buf-name (format "**cflow-%s:%s**"
                               (file-name-nondirectory trueFileName)
                               function-name))
  (setq cflow-buf (get-buffer-create cflow-buf-name))
  (set-buffer cflow-buf)
  (setq buffer-read-only nil)
  (erase-buffer)
  (insert (shell-command-to-string cmd))
  (pop-to-buffer cflow-buf)
  (goto-char (point-min))
  (cflow-mode)

Anyway,gald with your reply,Thanks!

**Comment by beacoder** [comment]
Hi,
thanks for your reply.
my original idea is that you need to fire up an emacs in the remote server
and listen to commands which
sent from local emacs.
so basically, local emacs will send commands like "global -a --result=grep
-r symbol" to remote over a UDP socket.
then remote received this command and execute it, return the result to
local.
the local will use this data to build the call-graph.

since this requires tweaking config for both local and remote emacs, which
is not that cool and convenient for the user.
so all in all, I don' think this brings too much value.

so.

Brs.


GitKKg ***@***.***> 于2021年7月30日周五 下午1:57写道：
