### ISSUE TITLE
Consider using cquery for function information

### ISSUE THREAD

**Issue by bizzyman** [beacoder/call-graph#4]
It seems that cquery project (https://github.com/cquery-project/cquery) has a native support for generating a call tree (just the back end, in other words it can yield the functions being called), would this be a more reliable way of generating call tree rather than using tags?

**Comment by beacoder** [comment]
thank you for recommending this great project to me, I will check it out.

**Comment by beacoder** [comment]
As this project is aiming for fast call-graph generation, so I will not introduce clang into this project.
instead I will try to work on other method to increase the call-graph accuracy.
So close it now.
