### ISSUE TITLE
Basic customization required

### ISSUE THREAD

**Issue by shmul** [beacoder/call-graph#5]
Looks like a promising package. Thanks.
A couple of comments:

- It should be possible to customize the location of the `global` binary
- It would be beneficial to process c files as well. This requires changing the command line in `call-graph--find-references` (which ideally should be customizable as well).
- The first invocation of `call-graph` worked ok, but subsequent ones showed the call graph of the first call, i.e. ignoring the function I actually invoked `call-graph` for. 

Cheers,
Shmul

**Comment by beacoder** [comment]
Thanks for your valuable advice, I will look into these later.
Currently, I'm more into the core feature development, so I have not pay too much attention about some of these customizations you mentioned, but I will come to these terms later, thanks again.

**Comment by beacoder** [comment]
The first invocation of call-graph worked ok, but subsequent ones showed the call graph of the first call, i.e. ignoring the function I actually invoked call-graph for.

@shmul , just fixed this one.

**Comment by shmul** [comment]
That's great. Thanks!
Since I'm installing the package via MELPA I'll wait for this fix to be published and then test it. BTW, till you handle the other two requests, I'll be forced to manually change the code to point at the right `global` binary and to process `C` files as well.

**Comment by beacoder** [comment]
@shmul ,

It should be possible to customize the location of the global binary
It would be beneficial to process c files as well. This requires changing the command line in call-graph--find-references (which ideally should be customizable as well).

Another commit was delivered to solve these two as well.
Please let me know if you have more questions, thanks.

**Comment by shmul** [comment]
Thanks for the prompt fixes. Things are working nicely for me. I will continue using it and report additional issues if/when encountered.

**Comment by beacoder** [comment]
@shmul , you're welcome, hope you enjoy it.
