### ISSUE TITLE
有没有兴趣做arbitrary symbol hierarchy (call, member, base/derived)

### ISSUE THREAD

**Issue by MaskRay** [beacoder/call-graph#6]
https://github.com/emacs-lsp/lsp-ui/issues/73

您可以从
https://github.com/cquery-project/cquery/wiki/Emacs
看起

这几个 language server protocol 的 cquery 扩展没有可视化

[$cquery/inheritanceHierarchy](https://github.com/cquery-project/cquery/blob/master/src/messages/cquery_inheritance_hierarchy.cc) is a kind of inheritance hierarchy (base/derived classes, base/overriden methods)
[$cquery/memberHierarchy](https://github.com/cquery-project/cquery/blob/master/src/messages/cquery_member_hierarchy.cc) is a kind of member hierarchy.
[$cquery/callerTreeInitial](https://github.com/cquery-project/cquery/blob/master/src/messages/cquery_call_tree.cc) is a kind of call hierarchy.

如果不需要树形可视化的化
[$cquery/derived](https://github.com/cquery-project/cquery/blob/master/src/messages/cquery_derived.cc)
[$cquery/base](https://github.com/cquery-project/cquery/blob/master/src/messages/cquery_base.cc)

就靠您了

https://emacs-china.org/t/topic/5131/2 看到的。也欢迎到 https://gitter.im/cquery-project/Lobby 讨论

**Comment by beacoder** [comment]
Someone recommended this cquery project to me before, I haven't got time to see it, definitely want to be part of this great project, if i'm qualified enough.
Disclaimer: due to the hot-key confliction, I did not install chine-input-method on my office PC, so using english instead.

**Comment by MaskRay** [comment]
Thanks!

**Comment by beacoder** [comment]
Thanks for the warmly invitation, but seems I can't squeeze that much time to contribute to other project.
Anyway, thanks again.
Close it now.

**Comment by MaskRay** [comment]
I should have closed this myself :) How time flies! topisani added this feature to emacs-cquery in February and later I ported it to emacs-ccls.

The interface doesn't look as good as tree-widget.el but it is more accurate powered by Clang C++ API https://github.com/MaskRay/ccls/wiki/lsp-mode#callmemberinheritance-hierarchies-----primary-templatepartial-specialization

**Comment by beacoder** [comment]
Haha, I wish all the best to ccls.
